# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Verbnet
version:      1.001
version_from: lib/Lingua/Verbnet.pm
installdirs:  site
requires:
    Pod::Usage:                    0
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
